### PR TITLE
remove null check operator from method ListenPhone

### PR DESCRIPTION
**Pull request by caio-deiro**
the null check has caused error in code with flutter 3.0.5 (current stable version) and would like this to be fixed 

image

### CODE REVIEW

**Comment by a-eniou-pvotal** [comment]
@caio-deiro you would need to increase the version number from version: 1.0.4 to 2.0.0
and add a new line to change logs to describe it 
I am not sure if you need to update min SDK or not!!

**Comment by caio-deiro** [comment]
> @caio-deiro you would need to increase the version number from version: 1.0.4 to 2.0.0 and add a new line to change logs to describe it I am not sure if you need to update min SDK or not!!

ok, i'll do it

**Review by amorenew — APPROVED** [review]
LGTM

**Comment by amorenew** [comment]
I will publish it tommorow

**Comment by amorenew** [comment]
Thanks a lot for your effort

**Comment by amorenew** [comment]
full migration would require

> This app is using a deprecated version of the Android embedding.
> To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
> Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
>

**Comment by caio-deiro** [comment]
do you have any prediction when you will be able to upgrade this package? Its possible update the project version  without running the android upgrade?

**Comment by amorenew** [comment]
@caio-deiro I will try to run it on my device tomorrow to see if it is still work fine or not

**Comment by amorenew** [comment]
I was busy today, I will try this weekend

**Comment by amorenew** [comment]
@caio-deiro sorry for the delay, I published it
https://pub.dev/packages/mobile_number/changelog

**Comment by caio-deiro** [comment]
thanks!!

**Pull request merged**
